INSERT INTO CATEGORY(NAME) VALUES ( 'Computers' );
INSERT INTO CATEGORY(NAME) VALUES ( 'Smartphones' );

INSERT INTO ITEM(CATEGORY_ID, NAME, PRICE)
    VALUES ((SELECT ID FROM CATEGORY WHERE NAME = 'Computers'), 'Apple Macbook Pro', 2300);

INSERT INTO ITEM(CATEGORY_ID, NAME, PRICE)
VALUES ((SELECT ID FROM CATEGORY WHERE NAME = 'Computers'), 'Lenovo X1 Carbon', 1800);

INSERT INTO ITEM(CATEGORY_ID, NAME, PRICE)
    VALUES ((SELECT ID FROM CATEGORY WHERE NAME = 'Smartphones'), 'Apple iPhone 11', 2300);

INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES('cosmin', 'abcd1234', 'MANAGEMENT');
INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES('andreea', 'abcd1234', 'MANAGEMENT');
INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES('raissa', 'abcd1234', 'MANAGEMENT');
INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES('andra', 'abcd1234', 'MANAGEMENT');
