CREATE TABLE CATEGORY(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME NVARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE ITEM(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    NAME NVARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL CHECK (PRICE > 0),
    CURRENT_DISCOUNT_PRC DOUBLE NOT NULL DEFAULT 0 CHECK(CURRENT_DISCOUNT_PRC >= 0 AND CURRENT_DISCOUNT_PRC <= 100)
);

CREATE TABLE USER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME NVARCHAR(50) UNIQUE NOT NULL,
    PASSWORD NVARCHAR(50) NOT NULL,
    ROLE NVARCHAR(10) NOT NULL DEFAULT 'CUSTOMER'
);